/*
 * Created on 2023-01-21 ( 17:24:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.salesmanager.core.model.banner;

import java.io.Serializable;
import java.util.List;
import javax.persistence.*;

import com.salesmanager.core.model.common.audit.AuditListener;
import com.salesmanager.core.model.common.audit.AuditSection;
import com.salesmanager.core.model.common.audit.Auditable;
import com.salesmanager.core.model.generic.SalesManagerEntity;

/**
 * JPA entity class for "Bannergroups"
 *
 * @author Telosys
 *
 */
@Entity
@EntityListeners(value = AuditListener.class)
@Table(name="BannerGroups")
public class Bannergroups extends SalesManagerEntity<Integer, Bannergroups> implements Auditable{

    private static final long serialVersionUID = 1L;

	@Embedded
	private AuditSection auditSection = new AuditSection();
	
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="BannerGroupId", nullable=false)
    private Integer    bannergroupid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="Name", nullable=false, length=50)
    private String     name ;

    @Column(name="Description", length=250)
    private String     description ;


    //--- ENTITY LINKS ( RELATIONSHIP )
    @ManyToMany
    @JoinTable(name="BannerGroupBanners", 
      joinColumns=@JoinColumn(name="BannerGroupId", referencedColumnName="BannerGroupId"),
      inverseJoinColumns=@JoinColumn(name="BannerId", referencedColumnName="BannerId")
     )
    private List<Banners> listOfBanners ; 

    @Transient
	private boolean obsolete = false;//when all items are obsolete
    
	@Override
	public AuditSection getAuditSection() {
		return auditSection;
	}

	@Override
	public void setAuditSection(AuditSection audit) {
		this.auditSection = audit;
	}
	
	@Override
	public Integer getId() {
		return bannergroupid;
	}

	@Override
	public void setId(Integer id) {
		this.bannergroupid = id;
		
	}

    /**
     * Constructor
     */
    public Bannergroups() {
		super();
    }
    
    //--- GETTERS & SETTERS FOR FIELDS
    public void setBannergroupid( Integer bannergroupid ) {
        this.bannergroupid = bannergroupid ;
    }
    public Integer getBannergroupid() {
        return this.bannergroupid;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setDescription( String description ) {
        this.description = description ;
    }
    public String getDescription() {
        return this.description;
    }

    //--- GETTERS FOR LINKS
    public List<Banners> getListOfBanners() {
        return this.listOfBanners;
    } 

    //--- toString specific method
	@Override
    public String toString() { 
        StringBuilder sb = new StringBuilder(); 
        sb.append(bannergroupid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(description);
        return sb.toString(); 
    } 

}
